# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: The Dev Files
subtitle: Development Blog of Jonathan Bernardi
url: https://www.thedevfiles.com
author: Jonathan Bernardi
email: jon@jonbernardi.com

meta:
  description: Development Blog of Jonathan Bernardi
  keywords: php mysql database web programming development javascript


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: spekkionu
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Bitbucket
#bitbucket_user: spekkionu

# Linked IN
linkedin_url: jonathan-bernardi/57/318/99a

# Drupal
drupal_user: spekkionu
#drupal_user_id: 429517

# Wordpress
#wordpress_user: spekkionu

# Trello
#trello_user: jonbernardi

# Twitter
twitter_user: thejonbernardi
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: 116642652326925126482
googleplus_hidden: true

youtube_user: spekkionu
#youtube_channel: UCW0rjRaOQEkEdHNw0m0WGPA

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus:
  shortname: thedevfiles
  show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-35809975-1
google_analytics_domain: thedevfiles.com

# Google Tag Manager
google_tag_manager_id: GTM-KBZCND

# Facebook Like
facebook_like: false
facebook_layout: button_count
facebook_url:

# Gravatar
gravatar:
  email: spekkionu@spekkionu.com
  hash: 7a5252ed2b4a12954535820e06fd0faa
