sculpin:
    ignore:
      - "**/*~"
      - "resources/**"
sculpin_pagination:
    max_per_page: 10
sculpin_content_types:
    posts:
        permalink: :year/:month/:filename/
jb_date_navigation:
    permalink_year: /:year/
    permalink_month: /:year/:month/

jb_tag_cloud:
    tag_permalink: /tag/:taxon/
    tag_entity: Jb\Bundle\TagCloudBundle\Model\Tag
    tag_cloud_entity: Jb\Bundle\TagCloudBundle\Model\TagCloud
    max_number: 0
    strategies:
        - jb_sculpin.tag_cloud.strategy.shuffle
        - jb_sculpin.tag_cloud.strategy.percent_size
